server:
  port: 8083
spring:
  datasource:
#    url: jdbc:mysql://rds8l3889yql6705lkkepublic.mysql.rds.aliyuncs.com:3306/pomp?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    url: jdbc:mysql://152.136.145.193:3306/free_school?characterEncoding=utf8&useSSL=false
    username: root
#    username: pmptest
    password: School@2018
#    password: zkdj_yqgj2)!&
  thymeleaf:
      cache: false
      check-template: true
      check-template-location: true
      enabled: true
      encoding: UTF-8
      excluded-view-names:
      mode: LEGACYHTML5
      prefix: classpath:/templates/
      suffix: .html
      template-resolver-order:

      servlet:
        content-type: text/html
  mvc:
    static-path-pattern: /static/**
templates:
  file-path:
    entity: entity/Entity.java
    repository: repository/Repository.java
    service: service/Service.java
    serviceImpl: service/impl/ServiceImpl.java