server:
  port: 8083
spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/pomp?characterEncoding=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: root
    hikari:
      connection-timeout: 30000
      idle-timeout: 60000
      max-lifetime: 1800000
      read-only: false
  thymeleaf:
      cache: false
      check-template: true
      check-template-location: true
      enabled: true
      encoding: UTF-8
      excluded-view-names:
      mode: LEGACYHTML5
      prefix: classpath:/templates/
      suffix: .html
  mvc:
    static-path-pattern: /static/**
templates:
  file-path:
    entity-template: entity/Entity.java
    repository-template: repository/Repository.java
    service-template: service/Service.java
    service-impl-template: service/impl/ServiceImpl.java
    dto-template: dto/Dto.java
    search-dto-template: dto/SearchDto.java
    controller-template: controller/Controller.java
    base-base-result-message-template: base/controller/BaseResultMessage.java
    base-result-message-template: base/controller/ResultMessage.java
    base-page-entity-template: base/entity/PageEntity.java
    base-base-service-template: base/service/BaseService.java
    base-constant-service-template: base/service/ConstantService.java
    base-interface-base-service-template: base/service/InterfaceBaseService.java
    base-page-utils-template: base/service/PageUtils.java