server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/pomp?autoReconnect=true&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
  thymeleaf:
      cache: false
      check-template: true
      check-template-location: true
      enabled: true
      encoding: UTF-8
      excluded-view-names:
      mode: LEGACYHTML5
      prefix: classpath:/templates/
      suffix: .html
      template-resolver-order:

      servlet:
        content-type: text/html
  mvc:
    static-path-pattern: /static/**
templates:
  file-path:
    entity: entity/Entity.java
    repository: repository/Repository.java
    service: service/Service.java
    serviceImpl: service/impl/ServiceImpl.java